// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxD0vJNBBe55-ujEpBAb9y9qoV6cNJpSU',
    appId: '1:1084532534550:web:8d7973e8249088a2b87437',
    messagingSenderId: '1084532534550',
    projectId: 'fir-ee372',
    authDomain: 'fir-ee372.firebaseapp.com',
    storageBucket: 'fir-ee372.firebasestorage.app',
    measurementId: 'G-L434W5SP2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUmazwzei0yCBMzHL_SBCCKb33MFQryw',
    appId: '1:827627617945:android:dfbc4054730981009cc208',
    messagingSenderId: '827627617945',
    projectId: 'kora-view',
    storageBucket: 'kora-view.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPupmI7sf-9yZf-SWJGvzVDBdhLB_iikM',
    appId: '1:1084532534550:ios:13b42f144e804a6fb87437',
    messagingSenderId: '1084532534550',
    projectId: 'fir-ee372',
    storageBucket: 'fir-ee372.firebasestorage.app',
    iosBundleId: 'com.example.monastery360app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPupmI7sf-9yZf-SWJGvzVDBdhLB_iikM',
    appId: '1:1084532534550:ios:13b42f144e804a6fb87437',
    messagingSenderId: '1084532534550',
    projectId: 'fir-ee372',
    storageBucket: 'fir-ee372.firebasestorage.app',
    iosBundleId: 'com.example.monastery360app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxD0vJNBBe55-ujEpBAb9y9qoV6cNJpSU',
    appId: '1:1084532534550:web:6852b83633f6b85eb87437',
    messagingSenderId: '1084532534550',
    projectId: 'fir-ee372',
    authDomain: 'fir-ee372.firebaseapp.com',
    storageBucket: 'fir-ee372.firebasestorage.app',
    measurementId: 'G-J10D874PJ9',
  );

}