name: Kora_View
description: A Flutter project for exploring monasteries.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

  # Mapping & Routing
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.2.1
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.3.0
  firebase_core: ^2.32.0 # Add this line

  # In-App Browser (WebView)
  webview_flutter: ^4.8.2
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.12.0

  # UI & Media
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  just_audio: ^0.9.37 # <-- Add this line
  flutter_launcher_icons: ^0.13.1 # <-- ADD THIS LINE



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"